services:  
  client:
    build: ./chat-app
    command: npm start
    volumes:
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - websocket_api  

  websocket_api:
    build: ./server
    command: python /app/src/server.py
    volumes:
      - ./server/src:/app/src
    ports:
      - "8000:8000"
